apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-nodejs
spec:
  replicas: 5
  selector:
    matchLabels:
      app: k8s-nodejs
  template:
    metadata:
      labels:
        app: k8s-nodejs
    spec:
      containers:
      - name: k8s-nodejs
        image: itsomondi/k8s-nodejs:3.0.0
        resources:
          limits:
            memory: "128Mi"
            cpu: "250m"
        ports:
        - containerPort: 3000
